# Generated by Django 4.2.6 on 2023-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField()),
                ('secret', models.TextField()),
                ('email', models.TextField()),
                ('mode', models.CharField(choices=[('sandbox', 'sandbox'), ('live', 'live')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
