# Generated by Django 4.2.6 on 2023-10-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paypal_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal',
            name='_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='secret',
            field=models.CharField(max_length=500),
        ),
    ]
