# Generated by Django 4.2.6 on 2023-10-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_paypal__id_alter_paypal_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypal',
            old_name='_id',
            new_name='cid',
        ),
    ]
